package com.example.izequiel;

import android.app.Activity;
import android.os.Bundle;
import android.widget.ArrayAdapter;
import android.widget.ListView;

public class ListaItinerarios extends Activity {

	private ListView lista;
	
	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.lista_itinerarios);
		
		 String[] values = new String[] { 
				 "011  Circular I",
				 "012  Circular II",
				 "013  Aguanambi I",
				 "014  Aguanambi II",
				 "015  Cj Ceará/Antônio Bezerra I",
				 "016  Cuca Barra/Papicu",
				 "017  Aldeota/Centro I (TopBus)",
				 "019  Messejana/Papicu/Manibura",
				 "020  Campus do Pici",
				 "021  Luciano Cavalcante/Papicu",
				 "022  Jardim das Oliveiras/Centro",
				 "023  Edson Queiroz/Papicu (Corujão)",
				 "024  Antônio Bezerra/Lagoa/Unifor",
				 "025  Opaia/Lagoa",
				 "026  Antônio Bezerra/Messejana",
				 "027  Siqueira/Papicu/Aeroporto",
				 "028  Antônio Bezerra/Papicu",
				 "029  Parangaba/Náutico",
				 "030  Siqueira/Papicu/13 de Maio",
				 "031  Av. Borges de Melo I",
				 "032  Av. Borges de Melo II",
				 "033  Circular I (Corujão)",
				 "034  Av. Paranjana I (Corujão)",
				 "035  Av. Paranjana II (Corujão)",
				 "036  Cj Ceará/Papicu/Montese (Corujão)",
				 "037  Cj Ceará/Aldeota (Corujão)",
				 "038  Parangaba/Papicu",
				 "039  Av. Bezerra de Menezes (Corujão)",
				 "040  Parangaba/Lagoa",
				 "041  Parangaba/Oliveira Paiva/Papicu",
				 "042  Antônio Bezerra/Francisco Sá/Papicu",
				 "043  Cj Ceará/Lagoa/Fernandes Távora",
				 "044  Parangaba/Papicu/Montese",
				 "045  Cj Ceará/Papicu/Montese",
				 "046  Cj Ceará (Corujão)",
				 "047  Av. José Bastos/Genibaú (Corujão)",
				 "048  Parangaba/Papicu (Corujão)",
				 "049  Caça e Pesca/Centro/Beira Mar (TopBus)",
				 "050  Siqueira/Papicu/Washington Soares",
				 "051  Grande Circular I",
				 "052  Grande Circular II",
				 "053  Messejana/Papicu/Washington Soares",
				 "054  Praia do Futuro/Caça e Pesca (Corujão)",
				 "055  Grande Circular I (Corujão)",
				 "056  Grande Circular II (Corujão)",
				 "057  Jardim Iracema  (Corujão)",
				 "058  Jardim Guanabara/Nova Ass II (Corujão)",
				 "059  Av. Sargento Herminio  (Corujão)",
				 "060  Parquelândia/Parangaba",
				 "061  Linha Central",
				 "062  Cj Esperança (Corujão)",
				 "063  Bom Jardim  (Corujão)",
				 "064  Corujão/Aeroporto/Centro/Rodoviária",
				 "065  Barroso/Jardim Violeta  (Corujão)",
				 "066  Parangaba/Papicu/Aeroporto",
				 "067  Lagoa/Albert Sabin",
				 "068  Messejana/Papicu/Cambeba",
				 "069  Lagoa/Papicu/Via Expressa",
				 "070  Cuca Barra/Parangaba/Centro",
				 "071  Antônio Bezerra/Mucuripe",
				 "072  Antônio Bezerra/Parangaba",
				 "073  Siqueira/Praia de Iracema (Dias úteis e sábados)",
				 "074  Antônio Bezerra/Unifor",
				 "075  Campus do Pici / Unifor",
				 "076  Cj Ceará/Aldeota",
				 "077  Parangaba/Mucuripe",
				 "078  Siqueira/Mucuripe ",
				 "079  Antônio Bezerra/Náutico",
				 "080  Fco Sá/Parangaba",
				 "081  Cj Ceará/Antônio Bezerra II",
				 "082  Antônio Bezerra/Messejana/Perimetral",
				 "083  Cj Ceará/Lagoa/Augusto dos Anjos",
				 "084  Siqueira/Messejana/Perimetral",
				 "085  Lagoa/Aldeota",
				 "086  Bezerra de Menezes/Santos Dumont",
				 "087  Expresso/Siqueira/Papicu",
				 "088  Antônio Bezerra/Albert Sabin",
				 "089  Expresso/Parangaba/Papicu",
				 "090  Montese (Corujão)",
				 "091  Expresso/Antônio Bezerra/Parangaba",
				 "092  Antônio Bezerra/Papicu/Praia de Iracema",
				 "093  Expresso/Messejana/Papicu",
				 "094  Expresso/Parangaba/Aldeota",
				 "095  Cj Pref José Walter (Corujão)",
				 "096  Cj Ceará/Barão de Studart",
				 "097  Antônio Bezerra/Siqueira",
				 "098  Expresso/Antônio Bezerra/Papicu",
				 "099  Siqueira/Mucuripe/Br. de Studart (Dias úteis)",
				 "101  Beira Rio",
				 "102  Vila Sto Ant/Nsa Sra Graças",
				 "108  Santa Maria/Bezerra Menezes",
				 "110  Vila do Mar/Centro",
				 "111  Jardim Iracema",
				 "112  Álvaro Weyne/Centro",
				 "114  Cj Nova Assunção/Fco Sá",
				 "115  Jardim Guanabara/Fco Sá",
				 "120  Vila do Mar/Antônio Bezerra",
				 "122  Antônio Bezerra/Álvaro Weyne",
				 "200  Av. Bezerra de Menezes (Dom)",
				 "201  Bezerra Menezes/Bairro Ellery",
				 "202  Rodolfo Teofilo/Bezerra Menezes",
				 "205  Dom Lustosa",
				 "206  Padre Andrade",
				 "210  Quintino Cunha/Antônio Bezerra",
				 "211  Vila Velha/Antônio Bezerra",
				 "212  Jardim Guanabara/Nova Ass I",
				 "213  Jardim Guanabara/Nova Ass II",
				 "214  Estação/Pio Saraiva I",
				 "215  Autran Nunes",
				 "216  Antônio Bezerra",
				 "217  Estação/Pio Saraiva II",
				 "220  Av. Sargento Herminio",
				 "225  João Arruda",
				 "233  Olavo Bilac/Bairro Ellery ",
				 "240  Quintino Cunha/Centro",
				 "243  Parque Universitários/Antônio Bezerra",
				 "250  Antônio Bezerra/Centro",
				 "251  Bezerra de Menezes/Coração de Jesus",
				 "300  Siqueira/Centro/Expresso",
				 "302  Rodolfo Teofílo/José Bastos",
				 "303  Igreja São Raimundo",
				 "304  Bela Vista/Lagoa",
				 "305  Bela Vista/Humberto Monte",
				 "307  Itaoca/Jardim América",
				 "308  Democrito Rocha",
				 "309  Cj Sumaré/Parangaba",
				 "310  Campus Universitários/Pan Americano",
				 "311  Castelão/Parangaba",
				 "311  Castelão/Parangaba",
				 "312  Dias Macedo/Parangaba",
				 "313  Parangaba/Alto da Paz",
				 "314  Henrique Jorge",
				 "315  Messejana/Parangaba",
				 "316  Genibaú/Centro",
				 "317  Cidade Nova/Parangaba",
				 "318  Av. Lineu Machado",
				 "319  Parque São Jose/Osório Paiva",
				 "320  João XXIII/Centro",
				 "321  Jardim União/Parangaba",
				 "322  Granja Portugal/Lagoa",
				 "323  João XXIII/Lagoa",
				 "324  1ª Etapa",
				 "325  Aracapé/Siqueira",
				 "327  4ª Etapa",
				 "329  Parque Santa Rosa/Siqueira",
				 "330  Cj Esperança/Siqueira",
				 "331  Cj Esperança/Centro",
				 "332  Siqueira/Lagoa",
				 "333  Bom Jardim/Centro/Expresso",
				 "334  Mondubim Siqueira I",
				 "335  Bom Jardim I",
				 "336  Parque Santa Cecilia I",
				 "337  Jardim Jatobá/Siqueira I",
				 "338  Canindezinho",
				 "339  Cj Veneza Tropical I/Parangaba",
				 "340  Cj Itapery",
				 "341  Cj Ceará I",
				 "342  Parque São Vicente",
				 "343  Cj Ceará II",
				 "344  Vila Betânia/Parangaba",
				 "345  Cj Ceará/Siqueira",
				 "346  Jardim Fluminense",
				 "347  Cj José Walter/Parangaba/Av. L",
				 "349  Cj Veneza Tropical II/Parangaba",
				 "350  Av. José Bastos/Lagoa",
				 "351  Jóquei/Bonsucesso",
				 "353  Parangaba/Parque Veras",
				 "355  Siqueira/José Bastos",
				 "356  Genibaú/Lagoa",
				 "357  Cj Ceará/Granja Lisboa",
				 "359  Santa Tereza",
				 "360  Siqueira/João Pessoa",
				 "361  Siqueira/Osório de Paiva/Parangaba",
				 "362  Siqueira/Vila Manoel Satiro/Parangaba",
				 "363  Vila Manoel Sátiro/Centro",
				 "365  Bela Vista/Viriato Ribeiro",
				 "366  Bom Jardim II",
				 "367  Cj Ceará/Bom Jardim",
				 "369  Parque Presidente Vargas",
				 "371  Parangaba/José Bastos",
				 "374  Aracapé/Centro",
				 "375  Aracapé/Parangaba I",
				 "376  Parque Santa Cecilia II",
				 "377  Cj José Walter/Parangaba/Av. J",
				 "378  Canindezinho/Urucutuba",
				 "379  Cj Esperança/Parangaba",
				 "381  Santa Maria/Siqueira",
				 "382  Parque Jerusalém",
				 "383  Parque São João/Siqueira",
				 "384  Parque Santana",
				 "385  Cj Ceará/Centro",
				 "386  Planalto Granja Lisboa",
				 "387  Jardim Jatobá/Centro/Expresso",
				 "388  Cj Tatu Mundé",
				 "389  Jovita Feitosa",
				 "390  Parangaba/João Pessoa",
				 "391  Passaré/Parangaba",
				 "392  Nova Esperança/Siqueira",
				 "393  Miguel Arraes/Siqueira",
				 "394  Parque Universitários/Lagoa I",
				 "395  Sítio Córrego/Parangaba",
				 "397  Jardim Jatobá/Siqueira II",
				 "401  Montese/Parangaba",
				 "403  Parangaba/Centro/Expedicionários",
				 "404  Aeroporto/Benfica",
				 "405  Parque Dois Irmãos/Expedicionários",
				 "406  Planalto Ayrton Senna/Expedicionários",
				 "407  Cj José Walter/Expedicionários",
				 "411  Montese/Lagoa",
				 "413  Parangaba/Expedicionários (Dias úteis)",
				 "456  Planalto Ayrton Senna/Parangaba",
				 "466  Arvoredo/Parangaba",
				 "501  Bairro de Fátima",
				 "502  Vila União",
				 "503  Av. 13 de Maio I",
				 "504  Av. 13 de Maio II",
				 "600  Messejana/Centro/Frei Cirilo",
				 "601  Aerolândia",
				 "602  Parque Pio XII/Ana Goncalves",
				 "603  Jardim União/Centro",
				 "604  Dias Macedo/Centro",
				 "605  Cj José Walter/Br 116/Av. I",
				 "606  Cj José Walter/Br 116/Av. N",
				 "609  Cidade Func/Sitio São José",
				 "610  Cidade dos Funcionários/Cj Alvorada",
				 "611  Cidade Func/Cofeco/Lago Jacarey",
				 "612  Cj Tancredo Neves/Lagamar",
				 "613  Barroso/Jardim Viôleta",
				 "616  Lagoa Redonda I",
				 "617  Lagoa Redonda/Abreulândia",
				 "618  Parque Santa Rosa/Messejana",
				 "619  Paupina",
				 "621  Pedras I",
				 "622  Pedras II",
				 "623  Santa Fé",
				 "625  Parque Manibura/Borges Melo",
				 "626  Lagoa Redonda II",
				 "627  Lagoa Redonda/Papicu",
				 "628  Sítio São João/Santa Maria",
				 "629  Cj Palmeiras/Perimetral",
				 "630  Itamaraty/Elizabeth II",
				 "631  Carlos Albuquerque",
				 "632  Alto Alegre/Messejana",
				 "633  Passaré/Centro",
				 "634  Lagoa Redonda/Abreulândia/Esquerda",
				 "635  Cj Tamandaré",
				 "636  Cj Palmeiras/Santa Maria",
				 "637  Cj Maria Tomásia/Santa Filomena",
				 "639  Planalto Coaçu/Messejana",
				 "640  Cj Alvorada/Messejana",
				 "641  Guajerú I",
				 "642  Guajerú II",
				 "643  Barroso Circular",
				 "645  João Paulo II",
				 "646  São Cristóvão",
				 "648  Cidade Nobre/Messejana",
				 "650  Messejana/Centro/Br Nova/Expresso",
				 "653  Santa Fé II (Dom)",
				 "655  Passaré/Messejana",
				 "656  Messejana/Sabiaguaba/Direita",
				 "657  Messejana/Sabiaguaba/Esquerda",
				 "660  Cj Palmeiras/Centro/Expresso",
				 "666  Jardim Castelão",
				 "670  Sítio São João/Centro/Expresso",
				 "676  Curió",
				 "686  São Bernardo",
				 "696  Sítio Curió/Messejana",
				 "701  Parque Americano",
				 "702  Av. Antônio Sales/Dionísio Torres",
				 "804  Aldeota",
				 "806  Edson Queiroz/Papicu",
				 "810  Papicu/Praia do Futuro (Dias",
				 "813  Papicu/Praia do Futuro II",
				 "814  Papicu/Castelo Encantado",
				 "815  Cidade Func/Papicu/Tancredo Neves",
				 "816  Edson Queiroz/Centro",
				 "820  Papicu/Cj Alvorada",
				 "825  Cidade Func/Papicu/Jardim das Oliveiras",
				 "831  Papicu/H Geral/Cidade 2000 (Dom)",
				 "832  Papicu/Cidade 2000",
				 "833  Cidade 2000/Centro",
				 "835  Defensoria/Papicu/Via Câmara",
				 "841  HGF/Papicu",
				 "901  Dom Luiz",
				 "903  Varjota",
				 "905  Meireles",
				 "906  Caça e Pesca/Serviluz/Centro",
				 "907  Castelo Encantado",
				 "913  Papicu/Serviluz/Varjota",
				 "920  Papicu/Caça e Pesca",
				 "703  Paupina/Pici (STPC)",
				 "705  Canindezinho/Iguatemi (STPC)",
				 "706  Edson Queiroz/Barra do Ceará (STPC)",
				 "709  Cj Ceará/Centro (STPC)",
				 "710  Cj Ceará/Bonsucesso/Centro (STPC)",
				 "711  Barra do Ceará/Cais do Porto (STPC)",
				 "712  Conjunto Palmeiras/Papicú (STPC)",
				 "713  Santos Dumont/Perimetral (STPC)",
				 "725  Parque Santa Maria/Liceu (STPC)",
				 "728  José Walter/Centro (STPC)",
				 "752  Caça e Pesca/Centro (STPC)",
				 "753  Cidade 2000/Sargento Herminio (STPC)",
				 "754  Granja Lisboa/Goiabeiras (STPC)",
				 "755  Conjunto Alvorada/North Shopping (STPC)",
				 "757  Vila Velha/Centro (STPC)",
				 "759  Conj. Palmeiras/Centro (STPC)"
                };
		
		
		lista = (ListView) findViewById(R.id.lista);
		lista.setAdapter(new ArrayAdapter<String>(this, android.R.layout.simple_list_item_1, values));
		
		
	}
	
	

}
